version: '3'

networks:
  rolelive-net:
    driver: bridge

services:

# Python
  rolelive:
    build:
      context: ./dockerfile
    volumes:
      - ./../rolelive2.py:/code/app.py
    restart: always
    networks:
      - rolelive-net
# Memcached
  memcached:
    image: 'bitnami/memcached:latest'
    environment:
      MEMCACHED_MAX_CONNECTIONS: "${MEMCACHED_MAX_CONNECTIONS}"
      MEMCACHED_THREADS: "${MEMCACHED_THREADS}"
      MEMCACHED_USERNAME: "${MEMCACHED_USERNAME}"
      MEMCACHED_PASSWORD: "${MEMCACHED_PASSWORD}"
    restart: always
    networks:
      - rolelive-net

# Postgres
  db:
     image: postgres:13-alpine
     environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
     volumes:
       - ./volumes/postgres/data:/var/lib/postgresql/data
     restart: always
     networks:
       - rolelive-net
