version: '3'

networks:
  rolelive-net:
    driver: bridge

services:

# Python
  python:
    image: 'oriolfilter/python-rolelive:first_try'
    volumes:
      - ./../rolelive2.py:/code/app.py
#    env_file:
#      - ./rolelive.env # rolelive v1
    restart: always
    networks:
      - rolelive-net
# Memcached
  memcached:
    image: 'bitnami/memcached:latest'
    environment:
      MEMCACHED_MAX_CONNECTIONS: "${MEMCACHED_MAX_CONNECTIONS}"
      MEMCACHED_THREADS: "${MEMCACHED_THREADS}"
      MEMCACHED_USERNAME: "${MEMCACHED_USERNAME}"
      MEMCACHED_PASSWORD: "${MEMCACHED_PASSWORD}"
#      - MEMCACHED_PASSWORD_FILE=file_with_admin_passwd
#    command: /opt/bitnami/scripts/memcached/run.sh -vvv
#    volumes:
#    - ./memcached.conf:/opt/bitnami/memcached/sasl2/memcached.conf
    restart: always
    networks:
      - rolelive-net

# Postgres
  db:
     image: postgres:13-alpine
     environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
     volumes:
       - ./volumes/postgres/data:/var/lib/postgresql/data
     restart: always
     networks:
       - rolelive-net
